### ISSUE TITLE
VETERAN STATUS

### ISSUE THREAD

**Issue by cookaa** [pittcsc/Summer2022-Internships#793]
Employment Visa Status does not work for certain websites.
<img width="810" alt="Screen Shot 2022-02-10 at 4 21 56 PM" src="https://user-images.githubusercontent.com/42782827/153498575-23480e2d-a581-407c-bb46-fb38b2589df7.png">

And SELF-IDENTIFICATION OF VETERAN STATUS does not always work.
<img width="869" alt="Screen Shot 2022-02-10 at 4 23 08 PM" src="https://user-images.githubusercontent.com/42782827/153498775-1be48a10-6d9b-4bdb-b563-ca9fc39b3e27.png">

I've noticed it can sometimes depend on the wording.

**Comment by canjianchen** [comment]
I don’t need sponsor , and also not a veteran . Thank you


On Feb 10, 2022, at 1:26 PM, Adam Cook ***@***.***> wrote:

﻿

Employment Visa Status does not work for certain websites.
[Screen Shot 2022-02-10 at 4 21 56 PM]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F42782827%2F153498575-23480e2d-a581-407c-bb46-fb38b2589df7.png&data=04%7C01%7Ccanjianchen%40cpp.edu%7C443f58e1082742a92d3608d9ecdbf9e2%7C164ba61e39ec4f5d89ffaa1f00a521b4%7C0%7C0%7C637801251816909959%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=GJq9AJ3oB6GaVXIBDdXNH7ewMIwgEeatHp3lU5bM3Qc%3D&reserved=0>

And SELF-IDENTIFICATION OF VETERAN STATUS does not always work.
[Screen Shot 2022-02-10 at 4 23 08 PM]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F42782827%2F153498775-1be48a10-6d9b-4bdb-b563-ca9fc39b3e27.png&data=04%7C01%7Ccanjianchen%40cpp.edu%7C443f58e1082742a92d3608d9ecdbf9e2%7C164ba61e39ec4f5d89ffaa1f00a521b4%7C0%7C0%7C637801251816909959%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=LrBihzKt8r1c1le8E6jeMwhh2Q9DB5mEMW2rmJx1N1c%3D&reserved=0>

I've noticed it can sometimes depend on the wording.

—
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpittcsc%2FSummer2022-Internships%2Fissues%2F793&data=04%7C01%7Ccanjianchen%40cpp.edu%7C443f58e1082742a92d3608d9ecdbf9e2%7C164ba61e39ec4f5d89ffaa1f00a521b4%7C0%7C0%7C637801251816909959%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=x578EtruNlV6Oe71hVvqUK7tF%2FNNJb%2FXiJp0Fqo0PdQ%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANECZ5D5K3SDKCMR4MIQYSLU2QUPTANCNFSM5OCDDPRA&data=04%7C01%7Ccanjianchen%40cpp.edu%7C443f58e1082742a92d3608d9ecdbf9e2%7C164ba61e39ec4f5d89ffaa1f00a521b4%7C0%7C0%7C637801251816909959%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Ab52LdC0jipx0VzTygTTpQwyal32C8ixhZttJbjps6Q%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ccanjianchen%40cpp.edu%7C443f58e1082742a92d3608d9ecdbf9e2%7C164ba61e39ec4f5d89ffaa1f00a521b4%7C0%7C0%7C637801251816909959%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=GI%2FSM3EOKAkFCKdLdDFxQTvFCRbEaTs8NxSlCg%2BTNDo%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ccanjianchen%40cpp.edu%7C443f58e1082742a92d3608d9ecdbf9e2%7C164ba61e39ec4f5d89ffaa1f00a521b4%7C0%7C0%7C637801251816909959%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=I5VfBpw7Zghdrm8Ckkkc4Q1YVjhpkcD9C7b%2Fl1vTtm8%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

CAUTION: This email was not sent from a Cal Poly Pomona service. Exercise caution when clicking links or opening attachments. Please forward suspicious email to ***@***.******@***.***>.
